[package]
name = "voiceover-server"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
serde = { version = "1.0.201", features = ["derive"] }
voiceover = { path = "../voiceover" }
serde_json = "1.0.117"
actix-web = "4.5.1"
actix-web-error = "0.2.0"
actix-cors = "0.7.0"